coverage:
  status:
    project:
      default:
        informational: true
      project-a:
        flags: project-a
      project-b:
        flags: project-b
    patch:
      default:
        informational: true

flags:
  package-a:
    paths:
      - packages/package-a
    carryforward: true
  package-b:
    paths:
      - packages/package-b
    carryforward: true

comment:
  layout: 'reach, diff, flags'
