flags:
  package-a:
    paths:
      - packages/package-a
    carryforward: true
  package-b:
    paths:
      - packages/package-b
    carryforward: true
coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 5%
      project-a:
        flags: project-a
      project-b:
        flags: project-b
    patch:
      default:
        informational: true
comment:
  layout: 'reach, diff, flags'
