name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test

      - uses: codecov/codecov-action@v1
        with:
          verbose: true
          directory: ./packages/package-a/coverage
          flags: project-b,unit

      - uses: codecov/codecov-action@v1
        with:
          verbose: true
          directory: ./packages/package-b/coverage
          flags: project-a,unit
